c_compiler_version:
  - 11

cxx_compiler_version:
  - 11

cuda_compiler:
  - nvcc

cmake_version:
  - ">=3.23.1,!=3.25.0"

sysroot_version:
  - "=2.17"

# The CTK libraries below are missing from the conda-forge::cudatoolkit
# package. The "*_host_*" version specifiers correspond to `11.8` packages and the
# "*_run_*" version specifiers correspond to `11.x` packages.

libcublas_host_version:
  - "=11.11.3.6"

libcurand_host_version:
  - "=10.3.0.86"

libcusolver_host_version:
  - "=11.4.1.48"

libcusparse_host_version:
  - "=11.7.5.86"

treelite_version:
  - "=3.1.0"
