c_compiler_version:
  - 9

cxx_compiler_version:
  - 9

cuda_compiler:
  - nvcc

cmake_version:
  - ">=3.23.1,!=3.25.0"

sysroot_version:
  - "=2.17"

# The CTK libraries below are missing from the conda-forge::cudatoolkit
# package. The "*_host_*" version specifiers correspond to `11.5` packages and the
# "*_run_*" version specifiers correspond to `11.x` packages.

libcublas_host_version:
  - ">=11.7.3.1,<=11.7.4.6"

libcurand_host_version:
  - ">=10.2.6.48,<=10.2.7.107"

libcusolver_host_version:
  - ">=11.2.1.48,<=11.3.2.107"

libcusparse_host_version:
  - ">=11.7.0.31,<=11.7.0.107"

treelite_version:
  - "=3.1.0"
