# Copyright (c) 2018, NVIDIA CORPORATION.

dist: trusty
sudo: required
language: python

branches:
    only:
        - master

env:
  global:
    - secure: 3BtcRmTAzNyuO/7n8LQbxz//+M+gv3OrKXJ7yOF/UugWpTjjuSvCOR5RYQl3/uLC5nAvpO3iutJuA9YFTmeGarYKcc/H3jBPhI51INHqr7EAZq9WnW+jYa0MqnlCDYvUUb1F3eeGbT7jl1rq7jAKoZa+3gLvM93MMk0IgVDmyFYqdp2jw/WcgDE7EwcqtJoH7bCMVmqUNtSGDfWa5j2ySCvsUisYHcOP0cTLQB9Em9N1axFkFSby0+HgXdq46oESjZv9sD1f5hSnafz6FLyI9JHdawtR+1HG6hh/8nClVgr0inSC5w5ie9OhaBHdCqmYXYlcwe5dTlDxU7VZ45UIjPc1ytdGXikSFgzlx3sTp6EHmRpbkfR6kqhTd6WyFM+W4BBM3pGp1ds5Gl9w1Q7ibClBzP+eAZ1y0JovQi2AjFWqPrUB/EovP38V1w332GAxvXU0EqwclBTE63q+8xpOkkN2P6NtlZtH3GnLx+Y3VN7PsMfoC8LG8T+3pOR7Y6iv45xoAAJEufR3iu6YmPGcayZDuekX4Q2luTCdqejevcZVeOFcgznkQRcIPatn9mcS+ahsNVu26ZvFKzTijyjK8JYN/Jo659BQ3CMN7RL5Ty5eRNU/2lBFs5kertEGWA5GX+gdChkpvoNEU7P2BTEf9S9GwfW9WEUPUirqLHu5kBA=

matrix:
  include:
    - env: CUDA=9.2.148_396.37 PYTHON=3.5 LABEL_MAIN=1 BUILD_CUML=1 BUILD_LIBCUML=1
    - env: CUDA=9.2.148_396.37 PYTHON=3.6 LABEL_MAIN=1 BUILD_CUML=1
    - env: CUDA=10.0.130_410.48 PYTHON=3.5 BUILD_CUML=1 BUILD_LIBCUML=1
    - env: CUDA=10.0.130_410.48 PYTHON=3.6 BUILD_CUML=1

before_install:
  # install build environment for libgdf
  - source ./travisci/install-env.sh
  # install miniconda
  - travis_retry wget --progress=dot:mega https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=$HOME/miniconda3/bin:$PATH

install:
  # check
  - conda --version
  # install conda build
  - travis_retry conda install conda-build anaconda-client flake8 conda-verify cmake=3.12.* --yes

script:
  # Activate root environment for cmake
  - source activate root
  # check conda versions
  - conda list
  # build cuML
  - source ./travisci/libcuml/build_libcuml.sh
  - source ./travisci/libcuml/upload-anaconda.sh
  - source ./travisci/cuml/build_cuml.sh
  - flake8 --exclude=cuML,ml-prims,__init__.py,versioneer.py

after_success:
  # upload cuML
  - source ./travisci/cuml/upload-anaconda.sh
