c_compiler_version:
  - 11

cxx_compiler_version:
  - 11

cuda_compiler:
  - cuda-nvcc

cuda11_compiler:
  - nvcc

sysroot_version:
  - "=2.17"

cmake_version:
  - ">=3.26.4"

treelite_version:
  - "=4.1.2"

gtest_version:
  - ">=1.13.0"

# The CTK libraries below are missing from the conda-forge::cudatoolkit package
# for CUDA 11. The "*_host_*" version specifiers correspond to `11.8` packages
# and the "*_run_*" version specifiers correspond to `11.x` packages.

cuda11_libcublas_host_version:
  - "=11.11.3.6"

cuda11_libcublas_run_version:
  - ">=11.5.2.43,<=11.11.3.6"

cuda11_libcusolver_host_version:
  - "=11.4.1.48"

cuda11_libcusolver_run_version:
  - ">=11.2.0.43,<=11.4.1.48"

cuda11_libcusparse_host_version:
  - "=11.7.5.86"

cuda11_libcusparse_run_version:
  - ">=11.6.0.43,<=11.7.5.86"

cuda11_libcurand_host_version:
  - "=10.3.0.86"

cuda11_libcurand_run_version:
  - ">=10.2.5.43,<=10.3.0.86"

cuda11_libcufft_host_version:
  - "=10.9.0.58"

cuda11_libcufft_run_version:
  - ">=10.5.0.43,<=10.9.0.58"
