c_compiler_version:
  - 11

cxx_compiler_version:
  - 11

cuda_compiler:
  - nvcc

sysroot_version:
  - "=2.17"

cmake_version:
  - ">=3.23.1,!=3.25.0"

treelite_version:
  - "=3.1.0"

gtest_version:
  - "=1.10.0"

# The CTK libraries below are missing from the conda-forge::cudatoolkit
# package. The "*_host_*" version specifiers correspond to `11.8` packages and the
# "*_run_*" version specifiers correspond to `11.x` packages.

libcublas_host_version:
  - "=11.11.3.6"

libcublas_run_version:
  - ">=11.5.2.43,<=11.11.3.6"

libcusolver_host_version:
  - "=11.4.1.48"

libcusolver_run_version:
  - ">=11.2.0.43,<=11.4.1.48"

libcusparse_host_version:
  - "=11.7.5.86"

libcusparse_run_version:
  - ">=11.6.0.43,<=11.7.5.86"

libcurand_host_version:
  - "=10.3.0.86"

libcurand_run_version:
  - ">=10.2.5.43,<=10.3.0.86"

libcufft_host_version:
  - "=10.9.0.58"

libcufft_run_version:
  - ">=10.5.0.43,<=10.9.0.58"
